---
title: "class"
author: "Lewis Zou"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(broom)
library(infer)
library(skimr)
```


```{r, cache = TRUE}
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "data.zip")

unzip("data.zip")

```


```{r}
my_list <- fs::dir_ls("2018-live-poll-results-master/data/")
  
raw <- map_dfr(my_list, read_csv, .id = "source", col_types = cols(
                                              .default = col_character(),
                                              turnout_scale = col_double(),
                                              turnout_score = col_double(),
                                              w_LV = col_double(),
                                              w_RV = col_double(),
                                              final_weight = col_double(),
                                              timestamp = col_datetime(format = "")
                                            ))


```

```{r}
x <- raw %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>%
  select(dvote, female, response, gender)
```

```{r}

# Relationship between dvote and female

ggplot(x, aes(female, dvote)) + geom_jitter(width = .1, height = .1) + geom_smooth(method = "glm")

# How can I use the model with the new data?

glm_obj <- glm(dvote ~ female, data = x, family = "binomial") 

# What is the female coefficient?

# Slight positive correlation between female and dvote, women are more likely than men to vote democratic

# Note that this is not a linear model

# Rule of four, you can divide the log regression by four to get the degree of change

# What is the meaning of the negative logarithmic intercept??


```



```{r}

test <- glm_obj %>% 
  tidy()

test
test[2,2]

my_data <- tibble(female = c(0,0, 1,1,0,0,0))

predict.glm(glm_obj, newdata = my_data, type = "response")


my_data2 <- x %>% 
  mutate(prob = predict.glm(glm_obj, type = "response"))

my_data2

```

```{r}

fs::file_delete(c("data.zip", "2018-live-poll-results-master/"))

```



